name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      # Make sure tags are fetched so we can get a version.
      - run: |
          git fetch --prune --unshallow --tags

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.2.2
        env:
          CIBW_BUILD_VERBOSITY: 3
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
